### ISSUE TITLE
Hi, nice project!

### ISSUE THREAD

**Issue by andryyy** [anbuhckr/abparser#2]
Hi, I am currently working on something called Kerkermeister, something like mailcow on steroids regarding privacy.

I am using this right now to do some cleanup in post-processing (before taking screenshots of the html body in Firefox over Tor in Selenium).

I this okay for you?

I plan to put the code online very soon for more people to work on it if they like, I'm also pretty new to Python after all... :)

You can also talk to me on Telegram @diekuh

**Comment by anbuhckr** [comment]
sure, go on!

closing this.
